### ISSUE TITLE
low contrast CZI logo

### ISSUE THREAD

**Issue by alisterburt** [napari/napari.github.io#146]
![image](https://user-images.githubusercontent.com/7307488/129766814-6e8072fd-ab0b-4c52-8b40-5516d393895f.png)
cc @sofroniewn - is there a version of the logo which looks better on dark backgrounds?

**Comment by sofroniewn** [comment]
yes, there is both

https://chanzuckerberg.com/wp-content/themes/czi/img/logo.svg

and

https://chanzuckerberg.com/wp-content/themes/czi/img/logo-white.svg

with black and white text respectively - i'm not sure how to automatically switch between them

Maybe @codemonkey800 can advise - this is for https://napari.org/community/team.html#funding-and-support

**Comment by codemonkey800** [comment]
The logo reference is here:

https://github.com/napari/napari.github.io/blame/03624a071bc232ab77f7a9b69a00c30e8e41a61a/community/team.md#L45

We would need to write some CSS that uses the [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) media query so we can switch between the logos depending on the user's theme preference.

Since we have some napari.org work planned soon, it might be a good chance to work on this issue 🤔

**Comment by neuromusic** [comment]
the new theme doesn't support dark mode, so this issue is no longer relevant. if/when we add support for dark mode (tracked in #253), we'll need to pay attention to alpha channels as part of that work.
