### ISSUE TITLE
replace embedded Google Calendar to address shortcomings

### ISSUE THREAD

**Issue by neuromusic** [napari/napari.github.io#271]
The embedded Google Calendar suffers from...

- an outdated UI
- which is inconsistent with our current designs
- and is not responsive etc

![image](https://user-images.githubusercontent.com/1245615/138515261-db4b32be-9c7a-4a64-8d41-86f7ec3dcfcb.png)

We should find a way to render the iCal in a way that is more user friendly & aligned with the site's design.

For reference...
- public link: https://calendar.google.com/calendar/embed?src=c_35r93ec6vtp8smhm7dv5uot0v4%40group.calendar.google.com
- calendar id: c_35r93ec6vtp8smhm7dv5uot0v4@group.calendar.google.com

**Comment by neuromusic** [comment]
some prior work: https://github.com/ericz1803/react-google-calendar

**Comment by kevinyamauchi** [comment]
Perhaps related: I think it would be nice if the calendar either showed times in the user’s time zone or had a user-settable time zone.

**Comment by neuromusic** [comment]
omg yes

**Comment by neuromusic** [comment]
@kevinyamauchi it looks like that react component I linked to renders the calendar in the user's timezone

**Comment by kevinyamauchi** [comment]
Nice!

**Comment by GenevieveBuckley** [comment]
> some prior work: https://github.com/ericz1803/react-google-calendar

This looks a lot better than the embedded google calendar!

I'd say these are the most important criteria, ordered from most to least important:
1. Displays events in the user's timezone
2. Easy to click and add a single event from it to your personal calendar
3. Easy to add the whole calendar so you can see it from your personal calendar (i.e. subscribe)
4. Works on desktop/tablet/mobile
5. Pretty

**Comment by GenevieveBuckley** [comment]
Link to a description of the first issue (not displaying events in the user's timezone) https://github.com/napari/napari/issues/3400

**Comment by isabela-pf** [comment]
I have some proposals on what this could look like visually to better match with the website theming (and with some ideas how it might work responsively). 

I also got feedback to focus on the monthly view for now, though that 7 by 5 grid doesn't fit well in narrow views.

These images will make this comment long, so if it's easier you can [view them all in Figma](https://www.figma.com/file/IpCKPRuLTxFEelZ8Rxgs6B/Calendar?node-id=18%3A136).

## Wide view

A pretty standard month in a grid. This essentially matches the default in `react-google-calendar` with styling changes.

The few things I've added
- The `Add Calendar` button is at the top before the visual. 
- The time zone footer lists which timezone it is pulling from browser settings
- Recurring events have a note about how they recur in the detailed view. (This is a wish-list item; I don't know if this info is in the Google Calendar API.)

<img width="1440" alt="napari's community page with a community calendar that matches the rest of the theming" src="https://user-images.githubusercontent.com/50221806/141530110-b852b204-3412-4ec5-84f9-61df5c82e448.png">

([A larger view of this calendar can be found here](https://www.figma.com/file/IpCKPRuLTxFEelZ8Rxgs6B/Calendar?node-id=18%3A136))

## Narrow view

I've seen two main behaviors for responsive calendars when they start with a wide month-level view:
- They scale proportionally, often getting too small to interact with well or cutting off the full view (that's what the Google calendar we have does now)
- They automatically switch out of month views to something that doesn't need a a large grid, like a week view.

Since we want to focus on month view for now, I'm proposing a list of events per month. Days without events are excluded to save vertical space. Weeks have a divider between them to give users something to ground themself with, especially if this list gets long.

Detailed event views are exactly the same.

<img width="500" alt="napari's community page with a community calendar that lists all events in a month" src="https://user-images.githubusercontent.com/50221806/141530724-18156311-c0e6-485e-b51a-2396f97c8d51.png">

As always, I'd love feedback on this and am happy to answer any questions you might have.

**Comment by isabela-pf** [comment]
I got some feedback from @liaprinsczi and wanted to update this issue with some of the modifications to each mockup.

Things that have changed:
- I missed that there was a secondary lighter blue in the napari.org and napari hub theme. It’s been added to the options here.
- The `today` indicator now encloses the number of the day. It’s also been added to the narrow view.
- The detailed view of an event has a point on the overlay to better indicate which event it is providing more information on.
- The narrow view now shows one week of events at a time so that it isn’t as long. This is important because even showing a long list with its own scroll may result in users needing to scroll through the whole list in order to get to the content below.
- Some text styles have been changed to create clearer hierarchy.

Here's how that might look in action:

https://user-images.githubusercontent.com/50221806/142587538-e748276f-03ef-4d03-a6c0-5f59cc154c9c.mov

https://user-images.githubusercontent.com/50221806/142587558-50183699-49bb-4b3e-8b44-c775ef468225.mov

And as static mockups:

<img width="1440" alt="napari community page with a month calendar." src="https://user-images.githubusercontent.com/50221806/142587693-46aa69e6-e164-49ae-a3ba-51e21da732bd.png">

<img width="500" alt="napari community page on a narrow screen with a week calendar." src="https://user-images.githubusercontent.com/50221806/142587706-6d0320fc-173c-4b2c-9804-9a128db54825.png">

**Comment by liaprins-czi** [comment]
This is shaping up really nicely I think! @neuromusic what do you think?

One other thing that'd be really useful to have, after talking to @sofroniewn about this work, is a really clear way to share the calendar or to the calendar section of that page.... maybe a "share this calendar" button or something similar?

**Comment by neuromusic** [comment]
This is looking great!

A few thoughts...

- the "Add calendar" copy initially read like a prompt soliciting me to add another calendar to this page, so we might want to revise that copy or icon (e.g. "Add to my calendar")
- I ❤️  the mobile view... compact, but clear. killer.


regarding quickly linking, I would suggest either...
- move the calendar to a separate page
- rely on the section header

the "quickly link to a section" challenge could be solved by either replacing the paragraph icon or supplementing it with a "copy" icon (for reference, Github suppressed the "link" icon until you hover over the heading, see e.g. https://github.com/chanzuckerberg/napari-hub/wiki/Roadmap-Guide)

**Comment by neuromusic** [comment]
the alternating black squares and blue circles are lovely and provide _just enough_ structure to differentiate the days. I love it.

I'm curious how effective it might be to bring some of those design elements back up to the "monthly" view? I see the blue circle... do you think the black square would be effective, too? do we really need the line separators in the monthly view?

**Comment by sofroniewn** [comment]
I love how this is progressing too. @isabela-pf gave a great demo in the last team meeting. @jni was very impressed too. As we both said we're constantly sharing the calendar link with folks and the calendar is one of the main ways that new folks can join the community.

One thought - and this might be too much - is to have the community meetings, the working groups, and "other" meetings all have three different colors, so it is very easy to tell them apart. What do folks think about this? I'm not sure, as it might feel messy, but when I'm inviting new people I often say something like "find the community meeting that is best for you given your timezone, we've got 3 times every 2 weeks", so it might be nice to make the super easy

**Comment by GenevieveBuckley** [comment]
> move the calendar to a separate page

+1 to this, if it's on a separate page it should be obvious from the sidebar menu  which one to click for the calendar.

> the "Add calendar" copy initially read like a prompt soliciting me to add another calendar to this page, so we might want to revise that copy or icon (e.g. "Add to my calendar")

+1 here too. Perhaps "Copy to my calendar" is clearest? I'd also suggest this should come before the event description, it's a bit easier to miss if it's at the very bottom & we want this to be pretty highly used.

**Comment by isabela-pf** [comment]
Thanks for all the feedback! I think I caught all the changes asked for above, but don’t hesitate to let me know if I missed something. 

First things first, here’s the updated mockups.

Wide view with filter and event details:

https://user-images.githubusercontent.com/50221806/143169711-4f6c61fb-9591-4da1-9981-83f558531938.mov

Narrow view with filter and event details:

https://user-images.githubusercontent.com/50221806/143169729-4fd17606-ddcd-411f-aaaa-6fe47ddce181.mov

And as still images:

<img width="1440" alt="Desktop view of the napari website with the community calendar showing details for a weekly community call." src="https://user-images.githubusercontent.com/50221806/143169816-7457a491-a36a-4dcb-a58d-fc1f34534c3a.png">

<img width="424" alt="Narrow view of the napari website with community calendar showing details for a weekly community call." src="https://user-images.githubusercontent.com/50221806/143169894-a17c74aa-21ef-4689-a871-8dfd094a162c.png">

<img width="424" alt="Narrow view of the napari website with community calendar showing the drop down filter button" src="https://user-images.githubusercontent.com/50221806/143169969-3e8b7bc9-84ff-41e4-bf48-e7632bb7cfd3.png">

I’ll be replying to feedback In no particular order:

- Could we have a more descriptive button name for adding the calendar to a personal calendar? Yep! It’s been updated to `Copy to my calendar` at the top of both.

- Does the wide calendar need the lines? I think it can work without since a monthly view is not too large of a grid to get lost in. The only problem I could see is making it slightly less clear which events belong to which day when a day’s list gets long.

- Could we make the square and circle for each day of the narrow view match the wide view? The blue circle for “today” was in the last round of monthly mockups, but the squares for each day were not. This is because the number of squares on the narrow view where only days with events are shown is much less than a full month. For reference, here’s what that looks like with squares for every day.
<img width="1207" alt="" src="https://user-images.githubusercontent.com/50221806/143170242-1573fc2c-c4d9-4b89-b725-601a6e483d28.png">
But I agree I’d like to have some way to reflect both for continuity if nothing else. I’ve tried a version where current week has all black square numbers (and the same blue “today” circle) as an in-between. This directly matches the narrow view and also provides a little more grounding when navigating the month view.

- Could we color code the type of event to make it easier to browse what events you’d like to attend. Color coding is tricky because color alone is not enough of an indicator for information (while I’d say this generally, it is also an accessibility concern per [WCAG 1.4.1](https://www.w3.org/TR/WCAG21/#use-of-color)). I do know exactly what you mean about struggling to mentally sort through the types of meetings, so I’ve proposed a list of checkboxes to filter types of events? This label could also appear in the detailed view so users have clarity on what type of meeting it is regardless of whether or not they take advantage of the filters.

- Could the calendars have a more clear/direct link? This I didn’t show yet. I agree most with having the calendar on its own page so it shows up in the sidebar navigation. I can confirm that I personally click around the community section a few times until I find the page I’m looking for, so I agree it could be more clear.

Let me know what other questions or comments you all have!

**Comment by GenevieveBuckley** [comment]
It's looking great!

Any chance we can make it say "Copy to my calendar" in the individual event descriptions too? That's what I was trying to refer to with my comment earlier, about the pop up details of specific events:
> +1 here too. Perhaps "Copy to my calendar" is clearest? I'd also suggest this should come before the event description, it's a bit easier to miss if it's at the very bottom & we want this to be pretty highly used.

Double checking - the "filter events" buttons are all ticked by default, right? So you can't accidentally miss events, unless you go and uncheck one of the boxes yourself? (I think that is the current situation, just wanted to be sure)

**Comment by isabela-pf** [comment]
Right, that was totally my misunderstanding; thanks for clarifying what you meant!

Does this set of event details fit better with what you were asking for? 

<img width="1207" alt="Detailed event view of a napari calendar event on the desktop size." src="https://user-images.githubusercontent.com/50221806/143320866-c1d59412-ee35-45c2-9c7d-dcc2d59cf87e.png">

<img width="424" alt="Detailed event view of a napari calendar event on the narrow size." src="https://user-images.githubusercontent.com/50221806/143320872-6fe553bc-8f67-41f2-b581-1a259636b07f.png">

> Double checking - the "filter events" buttons are all ticked by default, right? So you can't accidentally miss events, unless you go and uncheck one of the boxes yourself? (I think that is the current situation, just wanted to be sure)

That was absolutely my intention. It's good to make it clear that all events should be shown by default. Do you think the filter might run too high a risk of people accidentally selecting a filtered view and not realizing it, though?

**Comment by GenevieveBuckley** [comment]
> Does this set of event details fit better with what you were asking for?

Love it!

> Do you think the filter might run too high a risk of people accidentally selecting a filtered view and not realizing it, though?

If the filter settings are somehow saved with cookies, then maybe that could happen. If we're super worried about that possibility, maybe we could leave it out? There don't seem to be *that* many meetings to scroll through. I'm not worried about what gets decided here, I trust you to make reasonable judgement calls :smile:

**Comment by codemonkey800** [comment]
@isabela-pf this looks great, looking forward to implementing it! did you have any specific breakpoints in mind for when the docs should switch from the wide view to the narrow view?

**Comment by isabela-pf** [comment]
@codemonkey800 good question! I wasn't thinking of anything more specific than following the breakpoints the site already has. Basically, when the current implementation of the calendar begins getting cut off was when I would expect the calendar to switch from wide to narrow views. I think that's anything under 900px wide based on my rudimentary use of the browser inspector.

Is this a helpful reply, or do you think we need to account for a greater range of breakpoints?

**Comment by codemonkey800** [comment]
> I think that's anything under 900px wide based on my rudimentary use of the browser inspector.

I think this is good for now, but I'll let you know if I run into any weird issues that require additional breakpoints!

**Comment by codemonkey800** [comment]
PR has been opened! https://github.com/napari/napari.github.io/pull/302

**Comment by neuromusic** [comment]
reopening because the changes in #302 were overwritten

**Comment by codemonkey800** [comment]
This has been fixed by https://github.com/napari/napari/pull/3912:

https://napari.org/community/meeting_schedule.html

**Comment by kevinyamauchi** [comment]
The new calendar looks amazing! Thanks everyone !
